#Modify all lines indicated with MODIFY
outname: "AncInf" # MODIFY: prefix used for naming output
query: "PATH_TO_PLINK_PREFIX" #MODIFY: Prefix for PLINK files containing all of the query samples for ancestry inference
admixMapping:
  skip: 'true'
  rfmix: "OUTPUT_DIRECTORY_OF RFMIX" #MODIFY
  gen_since_admixture: '8'
  cores: '12'
  premunged: "false"
singularity:
  use_singularity: 'true'
  image: '/home/pmonnaha/pmonnaha/singularity/AncestryInference.sif' # MODIFY
  code: 'scripts/'
  module: 'module load singularity'
LD_pruning:
  window_size: "50"
  step_size: "5"
  r2_threshold: "0.3"
sHWE:
  pop_nums: '1,2,3,4,5,6' # From these choices, the pipeline will try to find the optimal number of populations to use in latent factor analysis used in the structured HWE procedure
  threshold: '0.000001' # p-value threshold for filtering based on departure from sHWE
  bins: '30'
  downsample_rounds: '2000'
  downsample_number: '1000'
  maf: '0.05'
  test_threshold: '500000'
IBD:
  maf: '0.05'
  cpj: '100000' # number of comparisons per job for IBS calculation
  pi_hat: '0.1875' # 0.1875 is suggested by doi: 10.1038/nprot.2010.116.
  ibd1: '0.2'
  filter_relateds: 'false' # This should be left as false.  No need to filter related individuals in BLINK or GENESIS.  However,
kinship_threshold: '0.125'  # Values below this are set to 0 (unrelated) in GENESIS
match_controls: 'false'
control_number: '4'
ancestry_predictors: 'AFR,EUR,AMR'
other_predictors: 'sex'  # this should include the variable names provided in covariate_file if those variables are desired to be included in the admixture mapping.
covariate_file: 'none' # Tab-delimited file with header line specifying names of covariates.  First column MUST be labeled with 'taxa' and should contain sample IDs EXACTLY as they are specified in input plink files.
samples: "all"  # This can be set to path of file containing individuals to be kept from merged query file. One sample per line.
cmd_prefix: "module load plink/1.90b6.10; module load htslib/1.6; module load bcftools/1.9;"
gwas:
  pc_num: '4'
  blink_dir: "/usr/local/bin/BLINK"
  cores: '12'
  sig_threshold: '0.000005'
  covars: 'sex'
run_settings:
  local_run: 'false'
  cluster_config: 'workflow/cluster.yaml'
  scheduler: 'pbs'
annotation:
  rsIDs: "/home/spectorl/pmonnaha/misc/hg19_rsID_key.txt"
conditional_analysis:
    snp_list: 'none'
    distance: '100000'